import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar for the API documentation site.
 *
 * The `api/`, `guides/`, and `specs/` folders are synced from the backend repo
 * by `scripts/sync-docs.mjs` — do not edit files inside those folders directly.
 */
const sidebars: SidebarsConfig = {
  apiSidebar: [
    'intro',
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'v1 (stable)',
          collapsed: false,
          items: [{type: 'autogenerated', dirName: 'api/v1'}],
        },
        {
          type: 'category',
          label: 'v2 (next)',
          items: [{type: 'autogenerated', dirName: 'api/v2'}],
        },
        'api/README',
        'api/versioning',
        'api/deprecation-template',
      ],
    },
    {
      type: 'category',
      label: 'Guides & Workflows',
      items: [{type: 'autogenerated', dirName: 'guides'}],
    },
    {
      type: 'category',
      label: 'Specs & Data Models',
      items: [{type: 'autogenerated', dirName: 'specs'}],
    },
  ],
};

export default sidebars;
