import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar for the API documentation site.
 *
 * The `api/`, `guides/`, and `specs/` folders are synced from the backend repo
 * by `scripts/sync-docs.mjs` — do not edit files inside those folders directly.
 * Clean labels/order come from the FRONTMATTER map in that script.
 *
 * This sidebar is explicit (not autogenerated) so the docs site presents a
 * curated information architecture instead of mirroring the backend's file
 * tree. Page URLs are unchanged — files keep their upstream paths.
 */
const sidebars: SidebarsConfig = {
  apiSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['getting-started/quickstart', 'getting-started/authentication'],
    },
    {
      type: 'category',
      label: 'API Reference',
      collapsed: false,
      items: [
        'api/README',
        {
          type: 'category',
          label: 'v1 (stable)',
          collapsed: false,
          items: [
            'api/v1/applicants',
            'api/v1/users',
            'api/v1/events',
            'api/v1/ocr',
            'api/v1/setup-token',
          ],
        },
        'api/v2/README',
        'api/versioning',
        'api/deprecation-template',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/workflows',
        'guides/workflows/applicant-tracking',
        'guides/workflows/auth-workflow',
        'guides/workflows/rbac',
        'guides/workflows/event-management',
        'guides/workflows/email-notifications',
      ],
    },
    {
      type: 'category',
      label: 'Data Models',
      collapsed: false,
      items: [
        'specs/data-models/overview',
        'specs/data-models/user',
        'specs/data-models/applicant',
        'specs/data-models/event',
        'specs/data-models/registration',
        'specs/data-models/sponsorship-inquiry',
      ],
    },
    {
      type: 'category',
      label: 'Project Docs',
      collapsed: true,
      items: ['specs/PRD-V1', 'specs/DTM'],
    },
  ],
};

export default sidebars;
